### ISSUE TITLE
Parser errors does not have the proper line number

### ISSUE THREAD

**Issue by gleamingthecube** [stephens2424/php#24] opened 2015-08-02 08:38 UTC
Parser errors always display line=0 instead of the real line number.

**Comment by aayushranaut** [comment] 2015-09-10 14:39
It seems to be working fine. Do you have code sample using which I can reproduce the issue?

**Comment by krageon** [comment] 2015-11-14 19:30
Have a look at https://github.com/stephens2424/php/blob/master/parser/parser.go#L225

There is no way that works properly. Something along the lines of ```e.Line = p.current.Begin.Line``` does appear to work properly.

**Comment by stephens2424** [comment] 2015-11-25 05:16
I think I broke this when I added support for multiple-file awareness in the parser.

**Comment by stephens2424** [comment] 2015-11-25 05:18
Should be fixed now. Fixed the filenames too.

**Closed by stephens2424** 2015-11-25 05:18 UTC
